<?php

namespace App\Install;

use InvalidArgumentException;

/**
 * Writes the .env file for a new installation.
 *
 * Unlike a find/replace on source files, this: (1) only writes a fixed
 * allowlist of keys, (2) quotes and escapes every value, (3) rejects control
 * characters outright so a value can never smuggle in extra lines/keys, and
 * (4) replaces the file atomically with owner-only permissions.
 */
class EnvWriter
{
    public const ALLOWED = [
        'APP_NAME', 'APP_ENV', 'APP_KEY', 'APP_DEBUG', 'APP_URL', 'APP_TIMEZONE', 'APP_LOCALE', 'APP_FALLBACK_LOCALE',
        'DB_CONNECTION', 'DB_HOST', 'DB_PORT', 'DB_DATABASE', 'DB_USERNAME', 'DB_PASSWORD',
        'SESSION_DRIVER', 'SESSION_LIFETIME', 'SESSION_COOKIE', 'SESSION_PATH', 'SESSION_SECURE_COOKIE', 'CACHE_STORE', 'QUEUE_CONNECTION', 'LOG_CHANNEL', 'LOG_LEVEL',
        'FOUNDATION_INSTALL_ID',
    ];

    public function __construct(private ?string $file = null)
    {
        $this->file ??= (string) config('foundation.env_file');
    }

    /** @param array<string,string|int|bool> $values */
    public function write(array $values): void
    {
        $lines = [];
        foreach ($values as $key => $value) {
            $lines[] = $key.'='.$this->format($key, $value);
        }

        $tmp = $this->file.'.'.bin2hex(random_bytes(4)).'.tmp';
        if (file_put_contents($tmp, "# Generated by the Foundation installer. Do not commit this file.\n".implode("\n", $lines)."\n", LOCK_EX) === false) {
            throw new \RuntimeException('Cannot write the .env file. Make the application folder writable.');
        }
        @chmod($tmp, 0600);
        if (! @rename($tmp, $this->file)) {
            @unlink($tmp);
            throw new \RuntimeException('Cannot replace the .env file. Check file permissions.');
        }
    }

    private function format(string $key, string|int|bool $value): string
    {
        if (! in_array($key, self::ALLOWED, true)) {
            throw new InvalidArgumentException("Refusing to write unknown configuration key [{$key}].");
        }
        if (is_bool($value)) {
            return $value ? 'true' : 'false';
        }
        $value = (string) $value;
        if (preg_match('/[\x00-\x1F\x7F]/', $value)) {
            throw new InvalidArgumentException("Configuration value for [{$key}] contains control characters.");
        }
        if ($value === '') {
            return '""';
        }
        if (preg_match('/^[A-Za-z0-9_.\/:@+\-]+$/', $value) && ! in_array(strtolower($value), ['true', 'false', 'null', 'yes', 'no', 'on', 'off'], true)) {
            return $value;
        }

        // Double-quoted: escape backslash, quote and $ (no variable interpolation).
        return '"'.str_replace(['\\', '"', '$'], ['\\\\', '\\"', '\\$'], $value).'"';
    }
}
