<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Synchronization metadata. Kept apart from business tables on purpose:
 * business rows describe the foundation's world; these describe how copies of
 * that world are reconciled.
 */
return new class extends Migration
{
    public function up(): void
    {
        // The change feed. `seq` is the pull cursor; `change_id` (a UUID generated by
        // the originating device) is the idempotency key - a retried push can never
        // apply twice because change_id is unique.
        Schema::create('sync_changes', function (Blueprint $table) {
            $table->bigIncrements('seq');
            $table->uuid('change_id')->unique();
            $table->string('entity', 64);
            $table->uuid('entity_id');
            $table->string('op', 10);                           // create | update | delete
            $table->unsignedInteger('version');
            $table->json('fields')->nullable();                 // names of business fields this change touched
            $table->json('payload')->nullable();                // what a puller applies
            $table->uuid('device_id')->nullable()->index();
            $table->uuid('user_id')->nullable();
            $table->timestamp('client_ts')->nullable();         // informational only; never used for ordering
            $table->timestamp('created_at', 6)->index();
            $table->index(['entity', 'entity_id', 'version']);
            $table->index(['entity', 'seq']);
        });

        // Changes that could not be applied without overwriting someone else's work.
        // The local change is preserved here; nothing is silently lost.
        Schema::create('sync_conflicts', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('change_id')->unique();
            $table->string('entity', 64);
            $table->uuid('entity_id');
            $table->string('op', 10);
            $table->uuid('device_id')->nullable();
            $table->uuid('user_id')->nullable();
            $table->unsignedInteger('base_version');
            $table->unsignedInteger('server_version');
            $table->string('reason', 40);                       // field_overlap | deleted_on_server | updated_on_server
            $table->json('conflicting_fields')->nullable();
            $table->json('local_payload')->nullable();
            $table->json('server_payload')->nullable();
            $table->string('status', 20)->default('open')->index(); // open | resolved
            $table->string('resolution', 30)->nullable();       // accept_server | accept_local | merged | server_wins | client_wins
            $table->uuid('resolved_by')->nullable();
            $table->timestamp('resolved_at')->nullable();
            $table->timestamps();
            $table->index(['entity', 'entity_id']);
        });
    }

    public function down(): void
    {
        // Intentionally non-destructive.
    }
};
