name: tests

on:
  push:
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_sqlite, gd, zip
          coverage: none
      - run: composer install --no-interaction --prefer-dist --no-progress
      - run: vendor/bin/phpunit
